/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import baseDatos.Conexion;
import baseDatos.OperacionesTabla;
import javax.swing.JOptionPane;

/**
 *
 * @author Yesica
 */
public class PnlProfesor extends javax.swing.JPanel {

    Conexion conexion;
    OperacionesTabla operaciones;

    /**
     * Creates new form pnlProfesor
     */
    public PnlProfesor() {
        initComponents();
        conexion = new Conexion();
        if (conexion.establecer("jdbc:mysql://localhost:3306/centromachor") == -1) {
            JOptionPane.showMessageDialog(null, "Errores en la base de datos");
            System.exit(-1);
        } else {
            operaciones = new OperacionesTabla(conexion);
        }
    }

    private void limpiar() {
        txtDni.setText("");
        txtNombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDni.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        txtDni.setForeground(new java.awt.Color(0, 51, 153));
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 220, 40));

        txtNombre.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 51, 153));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 220, 40));

        btnAceptar.setBackground(new java.awt.Color(153, 204, 255));
        btnAceptar.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 51, 153));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(153, 204, 255));
        btnCancelar.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 51, 153));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Dni");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Alta profesor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 290, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String dni = txtDni.getText();
        String nombre = txtNombre.getText();
        if (nombre.isBlank() || dni.isBlank()) {
            JOptionPane.showMessageDialog(this, "Rellene todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (operaciones.existeDni(dni)) {
                JOptionPane.showMessageDialog(this, "Ya existe un usuario con este dni", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                operaciones.crearProfesor(dni, nombre);
                JOptionPane.showMessageDialog(this, "Profesor dado de alta", "Información", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
