/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import baseDatos.Conexion;
import baseDatos.OperacionesTabla;

/**
 *
 * @author Yesica
 */
public class VtnOperaciones extends javax.swing.JFrame {

    PnlAula pnlAula;
    PnlConsulta pnlConsulta;
    PnlExamen pnlExamen;
    PnlProfesor pnlProfesor;
    Conexion conexion;
    OperacionesTabla operaciones;

    /**
     * Creates new form VtnOperaciones
     */
    public VtnOperaciones() {
        initComponents();
        this.setTitle("Gestión de exámenes");
        conexion = new Conexion();
        if (conexion.establecer("jdbc:mysql://localhost:3306/centromachor") == -1) {
            JOptionPane.showMessageDialog(null, "Errores en la base de datos");
            System.exit(-1);
        } else {
            operaciones = new OperacionesTabla(conexion);
        }
    }

    private void quitarPaneles() {
        fondo.setVisible(false);
        try {
            this.getContentPane().remove(pnlConsulta);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(pnlProfesor);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(pnlExamen);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(pnlAula);
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuProfesor = new javax.swing.JMenuItem();
        mnuAula = new javax.swing.JMenuItem();
        mnuExamen = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );

        getContentPane().add(jPanel1);

        jMenu1.setText("Gestión");

        mnuProfesor.setText("Alta profesor");
        mnuProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfesorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProfesor);

        mnuAula.setText("Alta aulas");
        mnuAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAulaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAula);

        mnuExamen.setText("Alta examen");
        mnuExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExamenActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExamen);

        mnuConsulta.setText("Consulta examenes");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu2.add(btnSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfesorActionPerformed
        quitarPaneles();
        pnlProfesor = new PnlProfesor();
        this.getContentPane().add(pnlProfesor);
        pack();
    }//GEN-LAST:event_mnuProfesorActionPerformed

    private void mnuAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAulaActionPerformed
        quitarPaneles();
        pnlAula = new PnlAula();
        this.getContentPane().add(pnlAula);
        pack();
    }//GEN-LAST:event_mnuAulaActionPerformed

    private void mnuExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExamenActionPerformed
        quitarPaneles();
        pnlExamen = new PnlExamen();
        this.getContentPane().add(pnlExamen);
        pack();
    }//GEN-LAST:event_mnuExamenActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        quitarPaneles();
        pnlConsulta = new PnlConsulta();
        this.getContentPane().add(pnlConsulta);
        pack();
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuAula;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuExamen;
    private javax.swing.JMenuItem mnuProfesor;
    // End of variables declaration//GEN-END:variables
}
